version: '2'
services:
    pms-app:
        image: pms
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://pms-postgresql:5432/pms
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    pms-postgresql:
        extends:
            file: postgresql.yml
            service: pms-postgresql
